base_url = "https://shroomkingdom.net"
title = "Shroom Kingdom"
description = "Shroom Kingdom is an upcoming play-to-earn earn video game built with web technologies running on the NEAR Blockchain."
default_language = "en"
# theme = ""
output_dir = "public"
compile_sass = true
build_search_index = true
minify_html = true
generate_feed = true
feed_filename = "atom.xml"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"
external_links_target_blank = true
external_links_no_referrer = true

[extra]
keywords = "shroom, mushroom, kingdom, super, mario, blockchain, gaming, playtoearn, play2earn, play, earn, near, protocol, nearprotocol"

[extra.team]
[extra.team.0]
name = "Mario Reder"
bio = "Full-stack developer who always had a fable for his side projects. Interested in everything about Rust and WebAssembly."
picture = "https://www.maibornwolff.de/sites/default/files/images/team/mariorederg.jpg"
twitter = "marior_dev"
github = "Tarnadas"
