name: Publish

on:
  push:
    branches: [develop]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Node dependencies
        run: yarn install
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Zola
        run: |
          cargo install --git https://github.com/getzola/zola.git
      - name: Publish
        run: |
          yarn gh-pages -d public -b master
