name: Publish

on:
  push:
    branches: [develop]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn install

      - name: Install Zola
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.14.0/zola-v0.14.0-x86_64-unknown-linux-gnu.tar.gz
          tar xvf zola-v0.14.0-x86_64-unknown-linux-gnu.tar.gz

      - name: Build site
        run: ./zola build

      - name: Publish
        run: |
          yarn gh-pages -d public -b master
